apiVersion: v1
kind: Service
metadata:
  name: agones-gameserver
  annotations:
    service.beta.kubernetes.io/volcengine-loadbalancer-pass-through: "true"
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: veloren-0
  ports:
  - protocol: TCP
    port: 14004 # local port
    targetPort: 14004
    name: game
  - protocol: TCP
    port: 7001
    targetPort: 8080
    name: metric
  externalTrafficPolicy: Local
